/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Employee = IDL.Record({
  'id' : IDL.Text,
  'fullName' : IDL.Text,
  'jobTitle' : IDL.Text,
});
export const Time = IDL.Int;
export const LeaveType = IDL.Variant({
  'sick' : IDL.Null,
  'vacation' : IDL.Null,
  'special' : IDL.Null,
});
export const LeaveEntry = IDL.Record({
  'date' : Time,
  'employeeId' : IDL.Text,
  'leaveType' : LeaveType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func([Employee], [], []),
  'addLeave' : IDL.Func([LeaveEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'deleteLeave' : IDL.Func([IDL.Text, Time], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
  'getEmployeeLeaves' : IDL.Func([IDL.Text], [IDL.Vec(LeaveEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchLeavesByRange' : IDL.Func(
      [IDL.Text, Time, Time],
      [IDL.Vec(LeaveEntry)],
      ['query'],
    ),
  'updateEmployee' : IDL.Func([Employee], [], []),
  'updateLeave' : IDL.Func([IDL.Text, Time, LeaveEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'fullName' : IDL.Text,
    'jobTitle' : IDL.Text,
  });
  const Time = IDL.Int;
  const LeaveType = IDL.Variant({
    'sick' : IDL.Null,
    'vacation' : IDL.Null,
    'special' : IDL.Null,
  });
  const LeaveEntry = IDL.Record({
    'date' : Time,
    'employeeId' : IDL.Text,
    'leaveType' : LeaveType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func([Employee], [], []),
    'addLeave' : IDL.Func([LeaveEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'deleteLeave' : IDL.Func([IDL.Text, Time], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [IDL.Opt(Employee)], ['query']),
    'getEmployeeLeaves' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaveEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchLeavesByRange' : IDL.Func(
        [IDL.Text, Time, Time],
        [IDL.Vec(LeaveEntry)],
        ['query'],
      ),
    'updateEmployee' : IDL.Func([Employee], [], []),
    'updateLeave' : IDL.Func([IDL.Text, Time, LeaveEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };