/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Employee {
  'id' : string,
  'fullName' : string,
  'jobTitle' : string,
}
export interface LeaveEntry {
  'date' : Time,
  'employeeId' : string,
  'leaveType' : LeaveType,
}
export type LeaveType = { 'sick' : null } |
  { 'vacation' : null } |
  { 'special' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEmployee' : ActorMethod<[Employee], undefined>,
  'addLeave' : ActorMethod<[LeaveEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'deleteLeave' : ActorMethod<[string, Time], undefined>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[string], [] | [Employee]>,
  'getEmployeeLeaves' : ActorMethod<[string], Array<LeaveEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchLeavesByRange' : ActorMethod<[string, Time, Time], Array<LeaveEntry>>,
  'updateEmployee' : ActorMethod<[Employee], undefined>,
  'updateLeave' : ActorMethod<[string, Time, LeaveEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];